FROM python:3.10


ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /facefusion

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN git clone https://github.com/wangping886/facefusion.git  .
RUN pip install -r requirements.txt
