FROM fusion-cpu-env:base
WORKDIR /facefusion
RUN git clone https://github.com/wangping886/facefusion.git --branch master --single-branch .
RUN mkdir fusioned
RUN pip install -r requirements.txt 
#or pip install flask  //gpu还需要注释onnx包

