FROM fusion-gpu-env:v2
RUN rm -rf /facefusion
WORKDIR /facefusion

RUN git clone https://github.com/wangping886/facefusion.git  .
#pip install -r requirements.txt or pip install flask  //gpu还需要注释onnx包

