FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
FROM python:3.10

ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /facefusion

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN git clone https://github.com/wangping886/facefusion.git  .
RUN pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118
RUN pip uninstall onnxruntime -y
RUN pip install onnxruntime-gpu==1.15.1
