name: ci

on: [ push, pull_request ]

jobs:
 test:
  name: facefusion-cpu
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - run: docker-compose -f docker-compose.cpu.yml up -d
  - run: docker-compose -f docker-compose.cpu.yml ps | grep -q facefusion-cpu
